apiVersion: al-assad.github.io/v1beta1
kind: DorisInitializer
metadata:
  name: basic-init
spec:
  # Target doris cluster name
  cluster: basic
  image: tnir/mysqlclient:1.4.6

  # The number of retries for the initialization script
  maxRetry: 3

  # Changes the default root & admin user password for Doris.(optional)
  rootPassword: ""
  adminPassword: ""

  # Doris initialization sql script.(optional)
  initSqlScript: |
    CREATE DATABASE IF NOT EXISTS DEMO;
    USE DEMO;
    CREATE TABLE IF NOT EXISTS demo.example_tbl(
      `user_id` LARGEINT NOT NULL,
      `date` DATE NOT NULL,
      `city` VARCHAR(20),
      `age` SMALLINT COMMENT,
      `sex` TINYINT COMMENT,
      `last_visit_date` DATETIME REPLACE DEFAULT "1970-01-01 00:00:00",
      `cost` BIGINT SUM DEFAULT "0",
      `max_dwell_time` INT MAX DEFAULT "0",
      `min_dwell_time` INT MIN DEFAULT "99999"
    )
      AGGREGATE KEY(`user_id`, `date`, `city`, `age`, `sex`)
      DISTRIBUTED BY HASH(`user_id`) BUCKETS 1
      PROPERTIES (
        "replication_allocation" = "tag.location.default: 1"
      );
    INSERT INTO example_tbl VALUES
      (1, '2021-01-01', 'Vienna', 18, 1, '2021-01-01 00:00:00', 20, 10, 10),
      (2, '2021-01-02', 'Frankfurt', 20, 1, '2021-04-01 6:00:00', 15, 2, 2),
      (3, '2021-05-02', 'Milan', 32, 0, '2021-07-01 23:00:00', 30, 11, 11),
      (4, '2021-06-12', 'Vienna', 22, 0, '2021-08-02 08:00:00', 11, 6, 6);
