[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Powered by <a class="text-muted" href="https://getdoks.org/">Doks</a> based on <a class="text-muted" href="https://gohugo.io/">Hugo</a>'

[zh]
  languageName = "Chinese"
  contentDir = "content/zh"
  weight = 15
  [zh.params]
    languageISO = "ZH"
    languageTag = "zh-CN"
    footer = 'Powered by <a class="text-muted" href="https://getdoks.org/">Doks</a> based on <a class="text-muted" href="https://gohugo.io/">Hugo</a>'
