# permissions for end users to view dorismonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dorismonitor-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: doris-operator
    app.kubernetes.io/part-of: doris-operator
    app.kubernetes.io/managed-by: kustomize
  name: dorismonitor-viewer-role
rules:
- apiGroups:
  - al-assad.github.io
  resources:
  - dorismonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - al-assad.github.io
  resources:
  - dorismonitors/status
  verbs:
  - get
