apiVersion: al-assad.github.io/v1beta1
kind: DorisMonitor
metadata:
  labels:
    app.kubernetes.io/name: dorismonitor
    app.kubernetes.io/instance: dorismonitor-sample
    app.kubernetes.io/part-of: doris-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: doris-operator
  name: dorismonitor-sample
spec:
  # TODO(user): Add fields here
