apiVersion: v1
kind: Service
metadata:
  name: {{ include "doris-operator.fullname" . }}-controller-manager-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: doris-operator
    app.kubernetes.io/part-of: doris-operator
    control-plane: controller-manager
  {{- include "doris-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "doris-operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metricsService.metricsPort }}
      protocol: TCP
      targetPort: metrics