apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "doris-operator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: doris-operator
    app.kubernetes.io/part-of: doris-operator
  {{- include "doris-operator.labels" . | nindent 4 }}